version: '3.0'

services:
  globus:
    build:
      context: .
      args:
        GUEST_GLOBUS_DATA_DIR: ${GUEST_GLOBUS_DATA_DIR}
    ports:
      - "2811:2811"
      - "${GRIDFTP_PORTS_LOW}-${GRIDFTP_PORTS_HIGH}:${GRIDFTP_PORTS_LOW}-${GRIDFTP_PORTS_HIGH}"
      - "7512:7512"
      - "443:443"
    command: ["./entry_point.sh"]
    environment:
      - GLOBUS_USER
      - GLOBUS_PASSWORD
      - SHORT_HOSTNAME
      - PUBLIC_HOSTNAME
      - GLOBUS_ACTIVATE_USER
      - GLOBUS_ACTIVATE_PASSWORD
      - GLOBUS_PERSISTENT
      - HOST_GLOBUS_DATA_DIR
      - GUEST_GLOBUS_DATA_DIR
      - GRIDFTP_PORTS_LOW
      - GRIDFTP_PORTS_HIGH
    volumes:
      - ./globus_state:/globus_state
      - ${HOST_GLOBUS_DATA_DIR}:${GUEST_GLOBUS_DATA_DIR}
