version: '3.0'

services:
  globus:
    build:
      context: .
    hostname: "${SHORT_HOSTNAME}"
    domainname: "${DOMAIN_NAME}"
    ports:
      - "2811:2811"
      - "50000-50010:50000-50010"
      - "7512:7512"
      - "443:443"
    command: ["./entry_point.sh"]
    environment:
      - GLOBUS_USER
      - GLOBUS_PASSWORD
      - SHORT_HOSTNAME
      - HOSTNAME
      - GLOBUS_ACTIVATE_USER
      - GLOBUS_ACTIVATE_PASSWORD
      - GLOBUS_PERSISTENT
    volumes:
      - ./globus_state:/globus_state
      - ./data:/data
