version: '3.0'

services:
  globus:
    build:
      context: .
    #hostname: "${SHORT_HOSTNAME}"
    #domainname: "${DOMAIN_NAME}"
    ports:
      - "${GRIDFTP_IP}:2811:2811"
      - "${PUBLIC_IP}:2811:2811"
      - "${GRIDFTP_IP}:50000-50100:50000-50100"
      - "${PUBLIC_IP}:50000-50100:50000-50100"
      - "${PUBLIC_IP}:7512:7512"
      - "${PUBLIC_IP}:443:443"
    command: ["./entry_point.sh"]
    environment:
      - GLOBUS_USER
      - GLOBUS_PASSWORD
      - SHORT_HOSTNAME
      - PUBLIC_HOSTNAME
      - GLOBUS_ACTIVATE_USER
      - GLOBUS_ACTIVATE_PASSWORD
      - GLOBUS_PERSISTENT
      - GLOBUS_DATA_DIR
      - GRIDFTP_IP
    volumes:
      - ./globus_state:/globus_state
      - ${GLOBUS_DATA_DIR}:/data
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9000
